# 禁用 daemon 模式
[supervisord]
nodaemon = true
user = %(ENV_USER)s

[supervisorctl]

[inet_http_server]
port = 127.0.0.1:9001

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

# php-fpm
[program:php-fpm]
process_name = %(program_name)s_%(process_num)s
command=/usr/local/sbin/php-fpm
user = %(ENV_USER)s
priority = 1
autostart=true
autorestart=true
stopasgroup = true
killasgroup = true
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile = /dev/stderr
stderr_logfile_maxbytes = 0

# horizon
[program:horizon]
process_name = %(program_name)s_%(process_num)s
command = php %(ENV_ROOT)s/artisan horizon
user = %(ENV_USER)s
priority = 2
autostart = true
autorestart = true
stopasgroup = true
killasgroup = true
stdout_logfile = %(ENV_ROOT)s/storage/logs/horizon.log
stdout_logfile_maxbytes = 20MB
stderr_logfile = %(ENV_ROOT)s/storage/logs/horizon.log
stderr_logfile_maxbytes = 20MB
stopwaitsecs = 3600

# 只執行一次，確保每次容器啟動時，排程快取都是乾淨的，避免舊快取影響新部署的排程任務。
[program:clear-scheduler-cache]
process_name = %(program_name)s_%(process_num)s
command = php %(ENV_ROOT)s/artisan schedule:clear-cache
user = %(ENV_USER)s
priority = 3
autostart = true
autorestart = false
startsecs = 0
startretries = 1
stdout_logfile = %(ENV_ROOT)s/storage/logs/scheduler.log
stdout_logfile_maxbytes = 20MB
stderr_logfile = %(ENV_ROOT)s/storage/logs/scheduler.log
stderr_logfile_maxbytes = 20MB

# scheduler
[program:scheduler]
process_name = %(program_name)s_%(process_num)s
command = supercronic -overlapping /etc/supercronic/laravel
user = %(ENV_USER)s
priority = 4
autostart = true
autorestart = true
stopasgroup = true
killasgroup = true
stdout_logfile = %(ENV_ROOT)s/storage/logs/scheduler.log
stdout_logfile_maxbytes = 20MB
stderr_logfile = %(ENV_ROOT)s/storage/logs/scheduler.log
stderr_logfile_maxbytes = 20MB

# nginx
[program:nginx]
process_name = %(program_name)s_%(process_num)s
command=/usr/sbin/nginx -g "daemon off;"
user = %(ENV_USER)s
priority = 5
autostart=true
autorestart=true
stopasgroup = true
killasgroup = true
stdout_logfile = %(ENV_ROOT)s/storage/logs/nginx.log
stdout_logfile_maxbytes = 20MB
stderr_logfile = %(ENV_ROOT)s/storage/logs/nginx.log
stderr_logfile_maxbytes = 20MB
